version: '3'
services:
  api:
    build:
      context: api
    working_dir: /usr/local/rucktar
    environment:
      DATABASE_URL: postgres://rucktar:whatever@db/rucktar
    volumes:
      - ./api:/usr/local/rucktar
      - ./crates:/usr/local/cargo/registry
    ports:
      - 3014:3014
    depends_on:
      - db
    command: tail -f /dev/null

  db:
    image: postgres:11-alpine
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rucktar
      POSTGRES_DB: rucktar
      POSTGRES_PASSWORD: whatever
    ports:
      - 5432

  adminer:
    image: adminer
    ports:
      - 3017:8080
