version: '3'
services:
  api:
    image: rust:1
    working_dir: /usr/local/rucktar
    environment:
      RUST_LOG: actix_web=debug
      DATABASE_URL: postgres://rucktar:whatever@db/rucktar
    volumes:
      - ./api:/usr/local/rucktar
      - ./crates:/usr/local/cargo/registry
    ports:
      - 3014:3014
    depends_on:
      - db
    command: cargo run

  frontend:
    build: ./frontend
    image: valerauko/node-jdk
    volumes:
      - ./frontend:/usr/local/rucktar
      - ./.m2:/root/.m2
    ports:
      - 9620:9620
      - 9630:9630
      - 9640:9640
    command: yarn run watch

  db:
    image: postgres:11-alpine
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rucktar
      POSTGRES_DB: rucktar
      POSTGRES_PASSWORD: whatever
    ports:
      - 5432

  adminer:
    image: adminer
    ports:
      - 3017:8080
