[package]
name = "api"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.2"
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }
chrono = { version = "0.4", features = ["serde"] }
serde = "*"
